icon: snap/gui/classipod.png
summary: Local Music Player Inspired by the iPod Classic
group: Applications/Multimedia
vendor: adeeteya
packager: Aditya R
packagerEmail: adeeteya@gmail.com
license: BSD-4-Clause
url: https://github.com/adeeteya/Classipod
requires:
  - mpv
  - mpv-libs
  - gtk3
  - glib2
  - gdk-pixbuf2
  - pango
  - cairo
  - atk
  - at-spi2-atk
  - libX11
  - libxkbcommon
  - libwayland-client
  - mesa-libEGL
  - libstdc++
  - sqlite-libs
  - xz-libs
  - libcurl
  - alsa-lib
  - xdg-utils
  - ca-certificates

display_name: Classipod

keywords:
  - Music
  - Audio
  - iPod
  - Local
  - Songs
  - Offline

generic_name: Local Music Player
categories:
  - Music

startup_notify: true
