display_name: Classipod
package_name: classipod
maintainer:
  name: Aditya
  email: adeeteya@gmail.com
priority: optional
section: x11
installed_size: 9280
essential: false
icon: snap/gui/classipod.png

dependencies:
  - mpv
  - libmpv1
  - libgtk-3-0
  - libglib2.0-0
  - libgdk-pixbuf-2.0-0
  - libpango-1.0-0
  - libpangocairo-1.0-0
  - libatk1.0-0
  - libatk-bridge2.0-0
  - libx11-6
  - libxkbcommon0
  - libwayland-client0
  - libegl1
  - libstdc++6
  - libsqlite3-0
  - liblzma5
  - libcurl4
  - libasound2
  - xdg-utils
  - ca-certificates

postinstall_scripts:
  - echo "Thanks for installing Classipod. If you like the app please give it a star on GitHub"
postuninstall_scripts:
  - echo "Sorry to see you go. If there are problems in the app please open an issue on GitHub"

keywords:
  - Music
  - Audio
  - iPod
  - Local
  - Songs
  - Offline

generic_name: Local Music Player

categories:
  - Music

startup_notify: true
